# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-16 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20180516_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='os',
            field=models.CharField(blank=True, max_length=30, verbose_name='系统类型'),
        ),
    ]
