# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-16 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_auto_20180516_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='cpu_p',
            field=models.CharField(blank=True, max_length=10, verbose_name='物理核心数'),
        ),
    ]
