remit-core:
  ip:
    - 10.10.203.109
    - 10.10.203.111
  svn_path: https://10.8.9.40/repo/remit-core
  rollback:
    1: remit-core-18872.1
    2: remit-core-18871.3
    3: remit-core-18870.4
    4: remit-core-18869.7
    5: remit-core-18869.7
    6: remit-core-18869.7
    7: remit-core-18869.7
  redis:
  ftp:
  oracle:

remit-gateway:
  ip:
    - 10.10.201.17
    - 10.10.201.19
  svn_path: https://10.8.9.40/repo/remit-gateway
  rollback:
    1: remit-gateway-18872.1
    2: remit-gateway-18871.3
    3: remit-gateway-18870.4
    4: remit-gateway-18869.7
    5: remit-gateway-18869.7
    6: remit-gateway-18869.7
    7: remit-gateway-18869.7
